# Generated by Django 5.1.1 on 2024-10-20 16:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptocurrency',
            options={'ordering': ('-last_updated',), 'verbose_name': 'Cryptocurrency', 'verbose_name_plural': 'Cryptocurrencies'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-timestamp',), 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['last_updated']},
        ),
        migrations.AddField(
            model_name='wallet',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
