# Generated by Django 5.1.1 on 2024-10-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_cryptocurrency_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='charge_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
