# Generated by Django 5.1.1 on 2024-11-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bitcoin_address',
            field=models.CharField(default=0, max_length=20, verbose_name='Bitcoin Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='ethereum_address',
            field=models.CharField(default=0, max_length=20, verbose_name='Ethereum Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='usdtc_address',
            field=models.CharField(default=1, max_length=20, verbose_name='USDTC Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
    ]
