# Generated by Django 5.1.1 on 2024-11-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_bitcoin_address_user_ethereum_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='charge_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='plan',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=0, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
