"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", cast=bool, default=False)

ALLOWED_HOSTS = ["127.0.0.1", "mywealthinvesments.pythonanywhere.com", "www.mywealthwiseinvest.com", "mywealthwiseinvest.mysql.pythonanywhere-services.com", "167.86.76.129"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "authentication",
    # 'users',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': config('DATABASE_ENGINE'),
        'NAME': config('DATABASE_NAME'),          # Your PythonAnywhere database name
        'USER': config("DATABASE_USER"),                  # Your PythonAnywhere username
        'PASSWORD': config('DATABASE_PASSWORD'),    # Your MySQL database password
        'HOST': config("DATABASE_HOST"),  # Host
        'PORT': '3306',                      # Default MySQL port
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Lagos'
USE_TZ = True  # This ensures Django uses timezone-aware datetimes

# TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

AUTH_USER_MODEL = "accounts.User"
LOGIN_URL = '/accounts/auth/login/'

AUTHENTICATION_BACKENDS = [
    'authentication.backends.CustomAuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
]


# Celery configuration
# CELERY_BROKER_URL = config("CELERY_BROKER_URL")
# CELERY_RESULT_BACKEND = config("CELERY_BROKER_URL")

CELERY_BROKER_URL='redis://:yKlVkKdFbCQceLf3wk0QZ0afA7a719fu@redis-10915.c257.us-east-1-3.ec2.redns.redis-cloud.com:10915/0'
CELERY_RESULT_BACKEND='redis://:yKlVkKdFbCQceLf3wk0QZ0afA7a719fu@redis-10915.c257.us-east-1-3.ec2.redns.redis-cloud.com:10915/0'

# Celery Beat settings
CELERY_BEAT_SCHEDULE = {
    'fetch-crypto-prices-every-5-minutes': {
        'task': 'accounts.tasks.fetch_crypto_prices_task',
        'schedule': 120.0,  # Every 5 minutes
    },
}


# settings.py

# # EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# # EMAIL_HOST = 'smtp.gmail.com'
# # EMAIL_PORT = config("EMAIL_PORT")
# # EMAIL_USE_TLS = config("EMAIL_USE_TLS", cast=bool, default=True)
# # EMAIL_HOST_USER = config("EMAIL_HOST_USER")
# # EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
# DEFAULT_FROM_EMAIL = 'MyWealthInvesments'

# Email settings for Zoho Mail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.zoho.com'
EMAIL_PORT = config("EMAIL_PORT", cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", cast=bool, default=True)
EMAIL_HOST_USER = config("EMAIL_HOST_USER")  # Your Zoho Mail email address
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")  # Your Zoho Mail password or app-specific password
DEFAULT_FROM_EMAIL = "admin@mywealthwiseinvest.com"  # The default from email address


ADMIN_EMAIL = "admin@mywealthwiseinvest.com"
COMPANY_NAME = 'MyWealthWise Investments'

COINBASE_API_KEY = config("COINBASE_API_KEY")


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [ os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
